import { ActionOpener } from 'services/models/Actions';
import { SkillInfoArgs, SkillResourceRequirement } from 'services/models/Skill';

export enum GnbSkills {
  KeenEdge = '3f09',
  BrutalShell = '3f0b',
  SolidBarrel = '3f11',
  DemonSlice = '3f0d',
  DemonSlaughter = '3f15',
  FatedCircle = '3f0d',
  SonicBreak = '3f19',
  LightningShot = '3f0f',
  GnashingFang = '3f12',
  SavageClaw = '3f13',
  WickedTalon = '3f16',
  JugularRip = '3f1c',
  AbdomenTear = '3f1d',
  EyeGouge = '3f1e',
  BurstStrike = '3f22',
  NoMercy = '3f0a',
  RoughDivide = '3f1a',
  BlastingZone = '3f25',
  BowShock = '3f1f',
  Bloodfest = '3f24',
}

export const Skills: Array<SkillInfoArgs> = [
  {
    name: 'Keen Edge',
    id: GnbSkills.KeenEdge,
    job: ['GNB'],
  },
  {
    name: 'Brutal Shell',
    id: GnbSkills.BrutalShell,
    job: ['GNB'],
  },
  {
    name: 'Solid Barrel',
    id: GnbSkills.SolidBarrel,
    job: ['GNB'],
  },
  {
    name: 'Demon Slice',
    id: GnbSkills.DemonSlice,
    job: ['GNB'],
  },
  {
    name: 'Demon Slaughter',
    id: GnbSkills.DemonSlaughter,
    job: ['GNB'],
  },
  {
    name: 'Fated Circle',
    id: GnbSkills.FatedCircle,
    job: ['GNB'],
    cooldown: 30000,
    requirements: [new SkillResourceRequirement(1, 'Cartridge')],
  },
  {
    name: 'Sonic Break',
    id: GnbSkills.SonicBreak,
    job: ['GNB'],
    cooldown: 60000,
  },
  {
    name: 'Lightning Shot',
    id: GnbSkills.LightningShot,
    job: ['GNB'],
  },
  {
    name: 'Gnashing Fang',
    id: GnbSkills.GnashingFang,
    job: ['GNB'],
    requirements: [new SkillResourceRequirement(1, 'Cartridge')],
  },
  {
    name: 'Savage Claw',
    id: GnbSkills.SavageClaw,
    job: ['GNB'],
  },
  {
    name: 'Wicked Talon',
    id: GnbSkills.WickedTalon,
    job: ['GNB'],
  },
  {
    name: 'Jugular Rip',
    id: GnbSkills.JugularRip,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 1000,
    type: 'Ability',
    requirements: [new SkillResourceRequirement(732, 'Buff')], // Ready to Rip
  },
  {
    name: 'Abdomen Tear',
    id: GnbSkills.AbdomenTear,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 1000,
    type: 'Ability',
    requirements: [new SkillResourceRequirement(732, 'Buff')], // Ready to Tear
  },
  {
    name: 'Eye Gouge',
    id: GnbSkills.EyeGouge,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 1000,
    type: 'Ability',
    requirements: [new SkillResourceRequirement(732, 'Buff')], // Ready to Gouge
  },
  {
    name: 'Burst Strike',
    id: GnbSkills.BurstStrike,
    job: ['GNB'],
    requirements: [new SkillResourceRequirement(1, 'Cartridge')],
  },
  {
    name: 'No Mercy',
    id: GnbSkills.NoMercy,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 60000,
    type: 'Ability',
  },
  {
    name: 'Rough Divide',
    id: GnbSkills.RoughDivide,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 30000,
    type: 'Ability',
    stocks: 2,
  },
  {
    name: 'Blasting Zone',
    id: GnbSkills.BlastingZone,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 30000,
    type: 'Ability',
  },
  {
    name: 'Bow Shock',
    id: GnbSkills.BowShock,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 60000,
    type: 'Ability',
  },
  {
    name: 'Bloodfest',
    id: GnbSkills.Bloodfest,
    job: ['GNB'],
    isOGCD: true,
    timer: 0,
    cooldown: 90000,
    type: 'Ability',
  },
];

export const Openers: ActionOpener[] = [{
  name: 'Standard Opener',
  sequenceIds: [
    GnbSkills.KeenEdge,
    GnbSkills.BrutalShell,
    GnbSkills.NoMercy,
    GnbSkills.SolidBarrel,
    GnbSkills.GnashingFang,
    GnbSkills.JugularRip,
    GnbSkills.RoughDivide,
    GnbSkills.SonicBreak,
    GnbSkills.BowShock,
    GnbSkills.BlastingZone,
    GnbSkills.SavageClaw,
    GnbSkills.Bloodfest,
    GnbSkills.AbdomenTear,
    GnbSkills.WickedTalon,
    GnbSkills.RoughDivide,
    GnbSkills.EyeGouge,
    GnbSkills.BurstStrike,
    GnbSkills.BurstStrike,
    GnbSkills.KeenEdge,
    GnbSkills.BrutalShell,
    GnbSkills.SolidBarrel,
  ]
}];